#!/bin/bash
set -euo pipefail

export W_RICCATI_SHOOTING_PATH="${W_RICCATI_SHOOTING_PATH:-5.0}"
export RICCATI_SHOOTING_PATH_POINTS="${RICCATI_SHOOTING_PATH_POINTS:-17}"
export RICCATI_SHOOTING_XI_BOUNDARY="${RICCATI_SHOOTING_XI_BOUNDARY:-0.985}"
export RICCATI_SHOOTING_PATH_XI_BOUNDARY="${RICCATI_SHOOTING_PATH_XI_BOUNDARY:-0.94}"
export RICCATI_SHOOTING_MATCH_START_EPOCH="${RICCATI_SHOOTING_MATCH_START_EPOCH:-200}"
export RICCATI_SHOOTING_PATH_START_EPOCH="${RICCATI_SHOOTING_PATH_START_EPOCH:-600}"
export RICCATI_SHOOTING_PATH_EVERY="${RICCATI_SHOOTING_PATH_EVERY:-10}"
export RICCATI_CI_LOCAL_MIN_START_EPOCH="${RICCATI_CI_LOCAL_MIN_START_EPOCH:-900}"
export LEARNING_RATE="${LEARNING_RATE:-2e-4}"
export GRAD_CLIP_NORM="${GRAD_CLIP_NORM:-1.0}"
export SEPARATE_BRANCH_OPTIMIZERS="${SEPARATE_BRANCH_OPTIMIZERS:-1}"
export DETACH_CI_IN_MODE_BRANCH="${DETACH_CI_IN_MODE_BRANCH:-1}"
export CI_BRANCH_LR="${CI_BRANCH_LR:-5e-5}"
export MODE_BRANCH_LR="${MODE_BRANCH_LR:-2e-4}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

bash scripts/run_kh_subsonic_singlecase_pure_physics_scalar_ci_matching_phaseA_bis.sh
